= DisroopEmbeddedHipster

image::https://github.com/disroop/DisroopEmbeddedHipster/actions/workflows/ci.yml/badge.svg[]

:uri-sonar: https://sonarcloud.io/dashboard?id=disroop_DisroopEmbeddedHipster
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_DisroopEmbeddedHipster&metric=bugs[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_DisroopEmbeddedHipster&metric=code_smells[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_DisroopEmbeddedHipster&metric=coverage[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_DisroopEmbeddedHipster&metric=duplicated_lines_density[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_DisroopEmbeddedHipster&metric=ncloc[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_DisroopEmbeddedHipster&metric=sqale_rating[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_DisroopEmbeddedHipster&metric=alert_status[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_DisroopEmbeddedHipster&metric=reliability_rating[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_DisroopEmbeddedHipster&metric=security_rating[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_DisroopEmbeddedHipster&metric=sqale_index[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_DisroopEmbeddedHipster&metric=vulnerabilities[Badge,link={uri-sonar}]

DisroopEmbeddedHipster is a showcase project which demonstrates how to create modern embedded applications with a modular architecture and implementing CI/CD practices.

These are the main features:

* Focusing on https://en.wikipedia.org/wiki/ARM_Cortex-M[ARM Cortex-M]
* Using https://hub.docker.com/u/disroop[Docker] to manage the toolchain
* Easy to setup developer environment in 10 seconds.
* Reproducible builds with a fully automated toolchain
* Use https://docs.conan.io/en/latest/[Conan as package manager]
* Use CMake in a https://cliutils.gitlab.io/modern-cmake/[Modern CMake] manner
* Use https://disroop.jfrog.io/[Artifactory] to manage artifacts
* Modular Architecture
* Testing (Unittest, Conan Package-Tests, Test on the Hardware)
* Supported unit testing frameworks (https://github.com/google/googletest[Gtest], https://github.com/catchorg/Catch2[Catch2], http://cpputest.github.io/[Cpputest])
* Use modern IDEs ( https://code.visualstudio.com/[VsCode] and https://www.jetbrains.com/de-de/clion/[Clion])
* Build-In Quality
    ** Code Analysis
    ** Coverage Analysis
    ** https://sonarcloud.io/organizations/disroop/projects?search=hipster[Sonar]

* Build Automation
    ** Project CLI with invoke
    ** https://github.com/disroop/DisroopEmbeddedHipster/actions[GitHub Actions]
    ** https://azure.microsoft.com/de-de/services/devops/pipelines/[Azure-Pipelines -todo]
    ** https://www.jenkins.io/[Jenkins -todo]

For more information read the <<doc/doc.adoc#,documentation>>



Try our VsCode extension

https://marketplace.visualstudio.com/items?itemName=disroop.conan

== Code Analysis

image:https://sonarcloud.io/images/project_badges/sonarcloud-black.svg[]




