= DisroopEmbeddedHipster
:toc:
:toc:
:toc: left
:toclevels: 3
:sectnums:
:sectnumlevels: 5


== System Requirements
DisroopEmbeddedHipster works on Linux, Windows and macOS.
You need https://www.docker.com/[Docker], https://www.python.org/[Python 3] and http://www.pyinvoke.org/[pyinvoke] preinstalled. All further installation can be done by command of the <<Project CLI>>.

== Getting Started
To get started run

[source,shell]
----
git clone https://github.com/disroop/DisroopEmbeddedHipster
code DisroopEmbeddedHipster
invoke vscode.open
----

This will clone the project and via the <<Project CLI>> open the project in VSCode.

NOTE:  The command open_in_vscode will install all missing dependencies linke VSCode, the required extension, ...

== Introduction

"Text relating to Overview from landing page"

- Automation
- Quality built in
- CI

=== Compiler
We need two outputs. A host build (x86) for running the unit tests and a ARM build for the final firmware.

==== Host

===== clang
clang is our primare compiler for the unittest builds.

===== gcc -> coming soon

-> feature coming soon

==== ARM
===== arm gcc
===== clang
feature coming soon
//see also https://labapart.com/blogs/3-the-importance-of-the-toolchain-version-in-embedded-space

===== iar
feature coming soon

== Infrastructure

Show an overview about

- local development
- Servers ( Artifactory, Build-Automation) For more informatino see
Learn how to organize the document into <<Build Automation>>.

== Debug on the HW
=== Segger
- Segger for St-Link

=== OpenOcd
feature coming soon


== Modular Architecture

DisroopEmbeddedHipster is build in a modular architecture. Modularity is the decomposition of the overall functionality into smaller pieces with standardized interfaces.


=== Conan Dependencies
As illustrated in <<blinky_dependencies>>, the application _blinky_ depends on the BSP (_stm32_bsp_iot_node_),
a runtime (_stm32_runtime_l475_vtg_)a runtime (_stm32_runtime_l475_vtg_).
Other modules


todo: explain _gcc_arm_none_eabi_ or remove this dependecy.


[[blinky_dependencies]]
.blinky conan dependencies
[graphviz, dot-example, svg]
----
include::conan_graph_blinky_debug.dot[]
----

The conan dependency tree in case of creating and running unit tests looks different. There the only dependency used is _gtest_. https://github.com/disroop/DisroopConanPackages/blob/master/recipes/cmake_vars/conanfile.py[cmake_vars] is a helper dependency which exports environment variables and options from a conanfile.

.utest conan dependencies
[graphviz, dot-example, svg]
----
include::conan_graph_utest.dot[]
----


=== Cmake Target Dependencies

.blinky cmake target dependencies
[graphviz, dot-example, svg]
----
include::../build/blinky-debug/cmake-target-graph.dot[]
----

.utest cmake target dependencies
[graphviz, dot-example, svg]
----
include::../build/utest/cmake-target-graph.dot[]
----


== CI/CD

Note: Continuous Delivery is coming in the future


== Build Automation
- Project CLI
- azure
- travis
- github actions
- jenkins


== Reproducibility

Was macht es reproduzierbar: Docker, Conan

== Project CLI

=== What is a Project CLI
WARNING: TODO: describe what a project cli is, what advantage it brings and how it is build

The Disroop Embeded Hipster Project is build with a https://interrupt.memfault.com/blog/building-a-cli-for-firmware-projects[Project CLI]

advantage

- executable documetnation. no need to read lond getting started instruction. just run
- tab complete for project cli with source <(inv --print-completion-script bash)

[source,shell]
----
git clone https://github.com/disroop/DisroopEmbeddedHipster
invoke setup
code DisroopEmbeddedHipster
----

The available command // use Font Awesome for admonition icons :icons: font

=== Commands



.project commands
----
include::../doc/project_commands.txt[]
----


.project commands
----
include::../doc/project_commands.txt[]
----

.vscode commands
----
include::../doc/vscode_commands.txt[]
----

.all command
----
include::../doc/all_commands.txt[]
----



The only preconditions are, that Docker and Python are installed.

== Quality-Built in

One of the important goals is to build quality in. This means a new developer does not need to read many pages of paper to get to know how some basic things like formatting the code, or what kind of coding rules exist.
Instead, he should be guided as much as possible with an automated solution. This is the aim of quality built in.

We manly use code compiler warnings, code formatters and code analysis tools. Those tools are run in the automated build and if possible we use IDE integration to prevent failing build and assist the developer instantly while editing code.

=== Compiler Warnings
The compiler warnings are the fist source for code analysis and should be the most important tool to assure the code quality.
We use https://clang.llvm.org/docs/UsersManual.html#id14[-Werror] to assure a minimal code quality must be maintained.
A more strick approache could be to use even more restictive settings linke -Wextra.

todo investigate what we should recommend: -Wall -Wextra -Werror? https://sourcegraph.com/search?q=context:global+-Wall+-Wextra+-Werror&patternType=literal
//https://quuxplusone.github.io/blog/2018/12/06/dont-use-weverything/
//https://github.com/llvm-mirror/clang/blob/master/include/clang/Basic/DiagnosticGroups.td
// https://clang.llvm.org/docs/UsersManual.html

=== ClangFormat
https://clang.llvm.org/docs/ClangFormat.html[ClangFormat] is a very popular code formatting tool with IDE integration in VSCode and CLion. +
We use a simple well curated Google style.

..clang-format
[source, c]
----
include::../.clang-format[]
----



=== Coverage Analysis
WARNING: todo

** in Build
** IDE Integration
//see https://marketplace.visualstudio.com/items?itemName=JacquesLucke.gcov-viewer
** define coverage limits

=== Code Analysis

=== clang-tidy
WARNING: todo

=== CPPCHECK
http://cppcheck.sourceforge.net/[Cppcheck]

WARNING: todo
==== include-what-you-use
WARNING: todo
https://include-what-you-use.org/[include-what-you-use]

=== Sonar
WARNING: todo

=== Dependabot
Stay up to date
WARNING: todo

=== Renovate
https://renovatebot.com/[Renovate] Stay up to date
WARNING: todo

=== Conclusion
Obviously one can not back all rules in an automated solutions as we showed in this chapter. But for those wehre an automated solution exist is server a great benefit.

=== Inspections / Code Analysis

== Unittests

//* continuous validation of releases with check sum on binary file

== Toolchain
=== Conan
=== Cmake
=== Unittest
=== Supported IDE

- VSCode
- CLion

=== Compiler
==== Host
===== clang
===== gcc

==== ARM
===== clang
===== arm gcc
===== iar


=== VsCode Conan Plugin
