= DisroopEmbeddedHipster
:toc:
:toc:
:toc: left
:toclevels: 3
:sectnums:
:sectnumlevels: 5


== System Requirements
DisroopEmbeddedHipster work on Linux, Windows and macOS.
You need https://www.docker.com/[Docker], https://www.python.org/[Python 3] and http://www.pyinvoke.org/[pyinvoke] preinstalled. All further installation can be done by command of the <<Project CLI>>.

== Getting Started
To get started run

[source,shell]
----
git clone https://github.com/disroop/DisroopEmbeddedHipster
code DisroopEmbeddedHipster
invoke open_in_vscode
----

This will clone the project and via the <<Project CLI>> open the project in VSCode.

NOTE:  The command open_in_vscode will install all missing dependencies linke VSCode, the required extension, ...

== Introduction

"Text relating to Overview from landing page"

- Automation
- Quality built in
- CI

=== Compiler
We need two outputs. A host build (x86) for running the unit tests and a ARM build for the final firmware.

==== Host

===== clang
clang is our primare compiler for the unittest builds.

===== gcc -> coming soon

-> feature coming soon

==== ARM
===== arm gcc
===== clang
feature coming soon
//see also https://labapart.com/blogs/3-the-importance-of-the-toolchain-version-in-embedded-space

===== iar
feature coming soon

== Infrastructure

Show an overview about

- local development
- Servers ( Artifactory, Build-Automation) For more informatino see
Learn how to organize the document into <<Build Automation>>.

== Debug on the HW
=== Segger
- Segger for St-Link

=== OpenOcd
feature coming soon


== Modular Architecture

BSP, CMSIS, ...

current state is simple but could be split in multiple packages

== CI/CD

Note: Continuous Delivery is coming in the future


== Build Automation
- Project CLI
- azure
- travis
- github actions
- jenkins


== Reproducibility

Was macht es reproduzierbar: Docker, Conan

== Project CLI
WARNING: TODO: describe what a project cli is, what advantage it brings and how it is build

The Disroop Embeded Hipster Project is build with a https://interrupt.memfault.com/blog/building-a-cli-for-firmware-projects[Project CLI]

advantage

- executable documetnation. no need to read lond getting started instruction. just run

[source,shell]
----
git clone https://github.com/disroop/DisroopEmbeddedHipster
invoke setup
code DisroopEmbeddedHipster
----

The only preconditions are that Docker and Python are installed.

== Quality-Built in

One of the important goals is to build quality in. This means a new developer does not need to read many pages of paper to get to know how some basic things like formatting the code, or what kind of coding rules exist.
Instead, he should be guided as much as possible with an automated solution. This is the aim of quality built in.

We manly use code formatters and code analysis tools. Those tools are run in the automated build and if possible we use IDE integration to prevent failing build and assist the developer instantly while editing code.

=== Compiler Warnings
The compiler warnings are the fist source for code analysis should be the most importatn too assure the code quality.
We use https://clang.llvm.org/docs/UsersManual.html#id14[-Werror] to assure a minimal code quality must be maintained.
A more strick approache coudl be to use even more restictive warnings linke -Wextra.

todo investigate what we should recommend: -Wall -Wextra -Werror? https://sourcegraph.com/search?q=context:global+-Wall+-Wextra+-Werror&patternType=literal
//https://quuxplusone.github.io/blog/2018/12/06/dont-use-weverything/
//https://github.com/llvm-mirror/clang/blob/master/include/clang/Basic/DiagnosticGroups.td
// https://clang.llvm.org/docs/UsersManual.html

=== ClangFormat
https://clang.llvm.org/docs/ClangFormat.html[ClangFormat] is a very popular code formatting tool with IDE integration in VSCode and CLion. +
We use a simple well curated Google style.

..clang-format
[source, c]
----
include::../.clang-format[]
----



=== Coverage Analysis
WARNING: todo

** in Build
** IDE Integration
** define coverage limits

=== Code Analysis

=== clang-tidy
WARNING: todo

=== CPPCHECK
http://cppcheck.sourceforge.net/[Cppcheck]

WARNING: todo
==== include-what-you-use
WARNING: todo
https://include-what-you-use.org/[include-what-you-use]

=== Sonar
WARNING: todo

=== Dependabot
Stay up to date
WARNING: todo

=== renovate
https://renovatebot.com/[Renovate] Stay up to date
WARNING: todo

=== Conclusion
Obviously one can not back all rules in an automated solutions as we showed in this chapter. But for those wehre an automated solution exist is server a great benefit.

=== Inspections / Code Analysis

== Unittests

//* continuous validation of releases with check sum on binary file

== Toolchain
=== Conan
=== Cmake
=== Unittest
=== Supported IDE

- VSCode
- CLion

=== Compiler
==== Host
===== clang
===== gcc

==== ARM
===== clang
===== arm gcc
===== iar


=== VsCode Conan Plugin
