name: Sonar Build
on:
  workflow_dispatch:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install docker

      - name: build & SonarCloud Scan
        run: python3 ./container-demo-build.py --sonartoken=${{ secrets.SONAR_TOKEN }}
