name: Sonar Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  
  workflow_dispatch:
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install docker 

      - name: build & SonarCloud Scan
        run: python3 ./container-demo-build.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
